# Ordered by priority
STREET_NAMES = [
    'STREET',
    'STRT',
    'ST',
    'STR',
    'ROAD',
    'RD',
    'ROADS',
    'RDS',
    'WAY',
    'WY',
    'AVENUE',
    'AV',
    'AVE',
    'AVEN',
    'AVENU',
    'AVN',
    'AVNUE',
    'DRIVE',
    'DR',
    'DRIV',
    'DRV',
    'GROVE',
    'GROV',
    'GRV',
    'LANE',
    'LN',
    'GARDENS',
    'GDNS',
    'GRDNS',
    'PLACE',
    'PL',
    'CRESCENT',
    'CRES',
    'CRSENT',
    'CRSNT',
    'CLOSE',
    'CLS',
    'SQUARE',
    'SQ',
    'SQR',
    'SQRE',
    'SQU',
    'HILL STREET',
    'HILL ROAD',
    'HILL',
    'HL',
    'HIGHWAY',
    'HWY',
    'TERRACE MEWS',
    'TERRACE',
    'MEWS',
    'TER',
    'TERR',
    'TCE',
    'VALE',
    'DENE',
    'RISE',
    'MEAD',
    'PARK ROAD',
    'PARK LANE',
    'PARK DRIVE',
    'PARK',
    'COURT',
    'ROW',
    'GATE',
    'WALK',
    'PARADE',
    'STATION ROAD',
]

STREET_ABBREVIATION_TO_NAME = {
    "ABBREVIATION": "FULLNAME",
    "STR": "STREET",
    "CRSNT": "CRESCENT",
    "DRIVE": "DRIVE",
    "DRV": "DRIVE",
    "DENE": "DENE",
    "AVNUE": "AVENUE",
    "STREET": "STREET",
    "CRESCENT": "CRESCENT",
    "HL": "HILL",
    "MEAD": "MEAD",
    "STRT": "STREET",
    "DR": "DRIVE",
    "GARDENS": "GARDENS",
    "WY": "WAY",
    "AVENU": "AVENUE",
    "LANE": "LANE",
    "AVEN": "AVENUE",
    "LN": "LANE",
    "AVENUE": "AVENUE",
    "DRIV": "DRIVE",
    "RD": "ROAD",
    "HILL": "HILL",
    "HWY": "HIGHWAY",
    "CLOSE": "CLOSE",
    "TER": "TERRACE",
    "TERR": "TERRACE",
    "ROAD": "ROAD",
    "TERRACE": "TERRACE",
    "GRV": "GROVE",
    "SQUARE": "SQUARE",
    "RDS": "ROADS",
    "CRSENT": "CRESCENT",
    "GROVE": "GROVE",
    "RISE": "RISE",
    "VALE": "VALE",
    "PLACE": "PLACE",
    "WAY": "WAY",
    "AV": "AVENUE",
    "GROV": "GROVE",
    "CLS": "CLOSE",
    "GDNS": "GARDENS",
    "GRDNS": "GARDENS",
    "SQR": "SQUARE",
    "SQ": "SQUARE",
    "CRES": "CRESCENT",
    "SQU": "SQUARE",
    "ST": "STREET",
    "AVN": "AVENUE",
    "PL": "PLACE",
    "ROADS": "ROADS",
    "AVE": "AVENUE",
    "SQRE": "SQUARE",
    "TCE": "TERRACE"
}
